name: Check

on: push

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint Check
        run: npm run lint

  test:
    needs: [lint]
    runs-on: self-hosted
    strategy:
      matrix:
        version: [20, 18, 22]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test
        env:
          PORT: ${{ secrets.PORT }}
